language: node_js
node_js: stable

install:
  - yarn install

script:
  - hexo g

after_script:
  - cd ./public
  - git init
  - git config user.name "romeo1992"
  - git config user.email 'romeo1992@163.com'
  - git add .
  - git commit -m "Update docs"
  - git push --force --quiet "https://${REPO_TOKEN}@${GH_REF}" master:gh-pages

branches:
  only:
    - master
env:
 global:
   - GH_REF: github.com/huxiaoxi1992/my-blog.git