language: node_js

node_js:
  - "node"

cache:
  directories:
    - node_modules

script:
  - hexo g

deploy:
  provider: pages
  skip-cleanup: true
  local-dir: public
  github-token: $GITHUB_TOKEN
  keep-history: true
  on:
    branch: master
